name: "Setup anchor-cli"
description: "Setup bun and anchor cli"
runs:
  using: "composite"
  steps:
    - uses: oven-sh/setup-bun@v2
    - uses: actions/cache@v4
      id: cache-anchor-cli
      with:
        path: ~/.cargo/bin/anchor
        key: anchor-cli-${{ runner.os }}-${{ env.ANCHOR_CLI_VERSION }}
    - if: steps.cache-anchor-cli.outputs.cache-hit != 'true'
      run: cargo install --git https://github.com/coral-xyz/anchor --tag v${{ env.ANCHOR_CLI_VERSION }} anchor-cli --locked
      shell: bash
